=== ChristianEhlers/Projekt1-sem2/xml/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="booksLibrary">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="books" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:string" name="sub_title"/>
              <xs:element type="xs:string" name="edition"/>
              <xs:element name="authors">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="author"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="publisher">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="year"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:short" name="pages"/>
              <xs:element type="xs:long" name="isbn"/>
              <xs:element type="xs:string" name="price"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ChristianEhlers/Projekt1-sem2/books.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<booksLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
  <books>
    <title>Get Programming With Node.js</title>
    <sub_title>test</sub_title>
    <edition>1st</edition>
    <authors>
      <author>Jonathan Wexler</author>
    </authors>
    <publisher>
      <name>Manning publications Co.</name>
      <year>2019</year>
    </publisher>
    <pages>438</pages>
    <isbn>9781617294747</isbn>
    <price>214,95</price>
  </books>
  <books>
    <title>Learning Web Design</title>
    <sub_title>A beginner's guide to HTML, CSS, JavaScript, and Web graphics</sub_title>
    <edition>5th</edition>
    <authors>
      <author>Jennifer Niederst Robbins</author>
    </authors>
    <publisher>
      <name>O'Reilly</name>
      <year>2018</year>
    </publisher>
    <pages>766</pages>
    <isbn>9781491960202</isbn>
    <price>259,95</price>
  </books>
  <books>
    <title>Visuel Kommunikation</title>
    <sub_title>PÃ¥ digitale medier</sub_title>
    <edition>1st</edition>
    <authors>
      <author>Lisbeth Thorlacius</author>
    </authors>
    <publisher>
      <name>Samfundslitteratur</name>
      <year>20187</year>
    </publisher>
    <pages>255</pages>
    <isbn>9788759326725</isbn>
    <price>229,95</price>
  </books>
  <books>
    <title>A new book title</title>
    <sub_title>A sub title for the new book</sub_title>
    <edition>5th</edition>
    <authors>
      <author>J.K. Rowling</author>
    </authors>
    <publisher>
      <name>Book Publishing Co.</name>
      <year>2020</year>
    </publisher>
    <pages>347</pages>
    <isbn>1234567890</isbn>
    <price>289,95</price>
  </books>
  <books>
    <title>A new book title</title>
    <sub_title>A sub title for the new book</sub_title>
    <edition>5th</edition>
    <authors>
      <author>Hans Christian Andersen</author>
    </authors>
    <publisher>
      <name>Book Publishing Co.</name>
      <year>2020</year>
    </publisher>
    <pages>347</pages>
    <isbn>1234567890</isbn>
    <price>289,95</price>
  </books>
  <books>
    <title>Another new book title</title>
    <sub_title>A new sub title for the new book</sub_title>
    <edition>5th</edition>
    <authors>
      <author>Karen Blixen</author>
    </authors>
    <publisher>
      <name>Book Publishing Co.</name>
      <year>2021</year>
    </publisher>
    <pages>587</pages>
    <isbn>1234567890</isbn>
    <price>289,95</price>
  </books>
</booksLibrary>
